-- CreateTable
CREATE TABLE "flat_bookings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "date" TEXT NOT NULL,
    "h8" INTEGER NOT NULL DEFAULT 1,
    "h9" INTEGER NOT NULL DEFAULT 1,
    "h10" INTEGER NOT NULL DEFAULT 1,
    "h11" INTEGER NOT NULL DEFAULT 1,
    "h12" INTEGER NOT NULL DEFAULT 1,
    "h13" INTEGER NOT NULL DEFAULT 1,
    "h14" INTEGER NOT NULL DEFAULT 1,
    "h15" INTEGER NOT NULL DEFAULT 1,
    "h16" INTEGER NOT NULL DEFAULT 1,
    "h17" INTEGER NOT NULL DEFAULT 1,
    "h18" INTEGER NOT NULL DEFAULT 1,
    "h19" INTEGER NOT NULL DEFAULT 1,
    "h20" INTEGER NOT NULL DEFAULT 1,
    "h21" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "flat_bookings_h8_fkey" FOREIGN KEY ("h8") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h9_fkey" FOREIGN KEY ("h9") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h10_fkey" FOREIGN KEY ("h10") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h11_fkey" FOREIGN KEY ("h11") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h12_fkey" FOREIGN KEY ("h12") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h13_fkey" FOREIGN KEY ("h13") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h14_fkey" FOREIGN KEY ("h14") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h15_fkey" FOREIGN KEY ("h15") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h16_fkey" FOREIGN KEY ("h16") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h17_fkey" FOREIGN KEY ("h17") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h18_fkey" FOREIGN KEY ("h18") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h19_fkey" FOREIGN KEY ("h19") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h20_fkey" FOREIGN KEY ("h20") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "flat_bookings_h21_fkey" FOREIGN KEY ("h21") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "username" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "EmployeeSales" (
    "salesId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "employeeName" TEXT NOT NULL,
    "month" TEXT NOT NULL,
    "salesAmount" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "bookings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "userid" INTEGER NOT NULL,
    "date" TEXT NOT NULL,
    "hour" INTEGER NOT NULL,
    CONSTRAINT "bookings_userid_fkey" FOREIGN KEY ("userid") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "memberDays" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "day" INTEGER NOT NULL,
    "member" INTEGER NOT NULL,
    CONSTRAINT "memberDays_member_fkey" FOREIGN KEY ("member") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
